export enum ApiErrorCode {
  UNHANDLED_ERROR = 'UNHANDLED_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  RATE_LIMITED = 'RATE_LIMITED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  TIMEOUT = 'TIMEOUT',
  NETWORK_ERROR = 'NETWORK_ERROR',
}

import { Language } from './language';

type ErrorMessagesMap = Record<ApiErrorCode, string>;

const messages: Record<Language, ErrorMessagesMap> = {
  [Language.English]: {
    [ApiErrorCode.UNHANDLED_ERROR]: 'An unexpected error occurred',
    [ApiErrorCode.BAD_REQUEST]: 'Invalid request',
    [ApiErrorCode.UNAUTHORIZED]: 'Authentication required',
    [ApiErrorCode.FORBIDDEN]: 'Access denied',
    [ApiErrorCode.NOT_FOUND]: 'Resource not found',
    [ApiErrorCode.CONFLICT]: 'Conflict occurred',
    [ApiErrorCode.METHOD_NOT_ALLOWED]: 'Method not allowed',
    [ApiErrorCode.VALIDATION_ERROR]: 'Validation failed',
    [ApiErrorCode.RATE_LIMITED]: 'Too many requests',
    [ApiErrorCode.INTERNAL_ERROR]: 'Internal server error',
    [ApiErrorCode.SERVICE_UNAVAILABLE]: 'Service unavailable',
    [ApiErrorCode.TIMEOUT]: 'Request timeout',
    [ApiErrorCode.NETWORK_ERROR]:
      'Unable to connect to the server. Please check your network connection.',
  },

  [Language.Spanish]: {
    [ApiErrorCode.UNHANDLED_ERROR]: 'Ha ocurrido un error inesperado',
    [ApiErrorCode.BAD_REQUEST]: 'Solicitud inválida',
    [ApiErrorCode.UNAUTHORIZED]: 'Autenticación requerida',
    [ApiErrorCode.FORBIDDEN]: 'Acceso denegado',
    [ApiErrorCode.NOT_FOUND]: 'Recurso no encontrado',
    [ApiErrorCode.CONFLICT]: 'Conflicto detectado',
    [ApiErrorCode.METHOD_NOT_ALLOWED]: 'Método no permitido',
    [ApiErrorCode.VALIDATION_ERROR]: 'Validación fallida',
    [ApiErrorCode.RATE_LIMITED]: 'Demasiadas solicitudes',
    [ApiErrorCode.INTERNAL_ERROR]: 'Error interno del servidor',
    [ApiErrorCode.SERVICE_UNAVAILABLE]: 'Servicio no disponible',
    [ApiErrorCode.TIMEOUT]: 'Tiempo de espera agotado',
    [ApiErrorCode.NETWORK_ERROR]: 'No se puede conectar al servidor. Verifique su conexión de red.',
  },

  [Language.SpanishLatinAmerica]: {
    [ApiErrorCode.UNHANDLED_ERROR]: 'Ha ocurrido un error inesperado',
    [ApiErrorCode.BAD_REQUEST]: 'Solicitud inválida',
    [ApiErrorCode.UNAUTHORIZED]: 'Autenticación requerida',
    [ApiErrorCode.FORBIDDEN]: 'Acceso denegado',
    [ApiErrorCode.NOT_FOUND]: 'Recurso no encontrado',
    [ApiErrorCode.CONFLICT]: 'Conflicto detectado',
    [ApiErrorCode.METHOD_NOT_ALLOWED]: 'Método no permitido',
    [ApiErrorCode.VALIDATION_ERROR]: 'Validación fallida',
    [ApiErrorCode.RATE_LIMITED]: 'Demasiadas solicitudes',
    [ApiErrorCode.INTERNAL_ERROR]: 'Error interno del servidor',
    [ApiErrorCode.SERVICE_UNAVAILABLE]: 'Servicio no disponible',
    [ApiErrorCode.TIMEOUT]: 'Tiempo de espera agotado',
    [ApiErrorCode.NETWORK_ERROR]: 'No se puede conectar al servidor. Verifique su conexión de red.',
  },

  [Language.French]: {
    [ApiErrorCode.UNHANDLED_ERROR]: "Une erreur inattendue s'est produite",
    [ApiErrorCode.BAD_REQUEST]: 'Requête invalide',
    [ApiErrorCode.UNAUTHORIZED]: 'Authentification requise',
    [ApiErrorCode.FORBIDDEN]: 'Accès refusé',
    [ApiErrorCode.NOT_FOUND]: 'Ressource non trouvée',
    [ApiErrorCode.CONFLICT]: 'Conflit détecté',
    [ApiErrorCode.METHOD_NOT_ALLOWED]: 'Méthode non autorisée',
    [ApiErrorCode.VALIDATION_ERROR]: 'Validation échouée',
    [ApiErrorCode.RATE_LIMITED]: 'Trop de requêtes',
    [ApiErrorCode.INTERNAL_ERROR]: 'Erreur interne du serveur',
    [ApiErrorCode.SERVICE_UNAVAILABLE]: 'Service indisponible',
    [ApiErrorCode.TIMEOUT]: 'Délai dépassé',
    [ApiErrorCode.NETWORK_ERROR]:
      'Impossible de se connecter au serveur. Vérifiez votre connexion réseau.',
  },

  [Language.German]: {
    [ApiErrorCode.UNHANDLED_ERROR]: 'Ein unerwarteter Fehler ist aufgetreten',
    [ApiErrorCode.BAD_REQUEST]: 'Ungültige Anfrage',
    [ApiErrorCode.UNAUTHORIZED]: 'Authentifizierung erforderlich',
    [ApiErrorCode.FORBIDDEN]: 'Zugriff verweigert',
    [ApiErrorCode.NOT_FOUND]: 'Ressource nicht gefunden',
    [ApiErrorCode.CONFLICT]: 'Konflikt erkannt',
    [ApiErrorCode.METHOD_NOT_ALLOWED]: 'Methode nicht erlaubt',
    [ApiErrorCode.VALIDATION_ERROR]: 'Validierung fehlgeschlagen',
    [ApiErrorCode.RATE_LIMITED]: 'Zu viele Anfragen',
    [ApiErrorCode.INTERNAL_ERROR]: 'Interner Serverfehler',
    [ApiErrorCode.SERVICE_UNAVAILABLE]: 'Dienst nicht verfügbar',
    [ApiErrorCode.TIMEOUT]: 'Zeitüberschreitung',
    [ApiErrorCode.NETWORK_ERROR]:
      'Keine Verbindung zum Server möglich. Bitte überprüfen Sie Ihre Netzwerkverbindung.',
  },

  [Language.Italian]: {
    [ApiErrorCode.UNHANDLED_ERROR]: 'Si è verificato un errore imprevisto',
    [ApiErrorCode.BAD_REQUEST]: 'Richiesta non valida',
    [ApiErrorCode.UNAUTHORIZED]: 'Autenticazione richiesta',
    [ApiErrorCode.FORBIDDEN]: 'Accesso negato',
    [ApiErrorCode.NOT_FOUND]: 'Risorsa non trovata',
    [ApiErrorCode.CONFLICT]: 'Conflitto rilevato',
    [ApiErrorCode.METHOD_NOT_ALLOWED]: 'Metodo non consentito',
    [ApiErrorCode.VALIDATION_ERROR]: 'Validazione fallita',
    [ApiErrorCode.RATE_LIMITED]: 'Troppe richieste',
    [ApiErrorCode.INTERNAL_ERROR]: 'Errore interno del server',
    [ApiErrorCode.SERVICE_UNAVAILABLE]: 'Servizio non disponibile',
    [ApiErrorCode.TIMEOUT]: 'Timeout scaduto',
    [ApiErrorCode.NETWORK_ERROR]:
      'Impossibile connettersi al server. Verifica la connessione di rete.',
  },

  [Language.Portuguese]: {
    [ApiErrorCode.UNHANDLED_ERROR]: 'Ocorreu um erro inesperado',
    [ApiErrorCode.BAD_REQUEST]: 'Requisição inválida',
    [ApiErrorCode.UNAUTHORIZED]: 'Autenticação necessária',
    [ApiErrorCode.FORBIDDEN]: 'Acesso negado',
    [ApiErrorCode.NOT_FOUND]: 'Recurso não encontrado',
    [ApiErrorCode.CONFLICT]: 'Conflito detectado',
    [ApiErrorCode.METHOD_NOT_ALLOWED]: 'Método não permitido',
    [ApiErrorCode.VALIDATION_ERROR]: 'Validação falhou',
    [ApiErrorCode.RATE_LIMITED]: 'Muitas requisições',
    [ApiErrorCode.INTERNAL_ERROR]: 'Erro interno do servidor',
    [ApiErrorCode.SERVICE_UNAVAILABLE]: 'Serviço indisponível',
    [ApiErrorCode.TIMEOUT]: 'Tempo esgotado',
    [ApiErrorCode.NETWORK_ERROR]:
      'Não foi possível conectar ao servidor. Verifique sua conexão de rede.',
  },

  [Language.ChineseSimplified]: {
    [ApiErrorCode.UNHANDLED_ERROR]: '发生意外错误',
    [ApiErrorCode.BAD_REQUEST]: '请求无效',
    [ApiErrorCode.UNAUTHORIZED]: '需要身份验证',
    [ApiErrorCode.FORBIDDEN]: '访问被拒绝',
    [ApiErrorCode.NOT_FOUND]: '资源未找到',
    [ApiErrorCode.CONFLICT]: '检测到冲突',
    [ApiErrorCode.METHOD_NOT_ALLOWED]: '方法不允许',
    [ApiErrorCode.VALIDATION_ERROR]: '验证失败',
    [ApiErrorCode.RATE_LIMITED]: '请求过多',
    [ApiErrorCode.INTERNAL_ERROR]: '服务器内部错误',
    [ApiErrorCode.SERVICE_UNAVAILABLE]: '服务不可用',
    [ApiErrorCode.TIMEOUT]: '请求超时',
    [ApiErrorCode.NETWORK_ERROR]: '无法连接到服务器。请检查您的网络连接。',
  },

  [Language.ChineseTraditional]: {
    [ApiErrorCode.UNHANDLED_ERROR]: '發生意外錯誤',
    [ApiErrorCode.BAD_REQUEST]: '請求無效',
    [ApiErrorCode.UNAUTHORIZED]: '需要身份驗證',
    [ApiErrorCode.FORBIDDEN]: '存取被拒絕',
    [ApiErrorCode.NOT_FOUND]: '資源未找到',
    [ApiErrorCode.CONFLICT]: '檢測到衝突',
    [ApiErrorCode.METHOD_NOT_ALLOWED]: '方法不允許',
    [ApiErrorCode.VALIDATION_ERROR]: '驗證失敗',
    [ApiErrorCode.RATE_LIMITED]: '請求過多',
    [ApiErrorCode.INTERNAL_ERROR]: '伺服器內部錯誤',
    [ApiErrorCode.SERVICE_UNAVAILABLE]: '服務不可用',
    [ApiErrorCode.TIMEOUT]: '請求逾時',
    [ApiErrorCode.NETWORK_ERROR]: '無法連接到伺服器。請檢查您的網路連線。',
  },

  [Language.Japanese]: {
    [ApiErrorCode.UNHANDLED_ERROR]: '予期しないエラーが発生しました',
    [ApiErrorCode.BAD_REQUEST]: '無効なリクエスト',
    [ApiErrorCode.UNAUTHORIZED]: '認証が必要です',
    [ApiErrorCode.FORBIDDEN]: 'アクセスが拒否されました',
    [ApiErrorCode.NOT_FOUND]: 'リソースが見つかりません',
    [ApiErrorCode.CONFLICT]: '競合が検出されました',
    [ApiErrorCode.METHOD_NOT_ALLOWED]: '許可されていないメソッド',
    [ApiErrorCode.VALIDATION_ERROR]: '検証に失敗しました',
    [ApiErrorCode.RATE_LIMITED]: 'リクエストが多すぎます',
    [ApiErrorCode.INTERNAL_ERROR]: 'サーバー内部エラー',
    [ApiErrorCode.SERVICE_UNAVAILABLE]: 'サービス利用不可',
    [ApiErrorCode.TIMEOUT]: 'リクエストタイムアウト',
    [ApiErrorCode.NETWORK_ERROR]: 'サーバーに接続できません。ネットワーク接続を確認してください。',
  },

  [Language.Korean]: {
    [ApiErrorCode.UNHANDLED_ERROR]: '예상치 못한 오류가 발생했습니다',
    [ApiErrorCode.BAD_REQUEST]: '잘못된 요청',
    [ApiErrorCode.UNAUTHORIZED]: '인증이 필요합니다',
    [ApiErrorCode.FORBIDDEN]: '접근이 거부되었습니다',
    [ApiErrorCode.NOT_FOUND]: '리소스를 찾을 수 없습니다',
    [ApiErrorCode.CONFLICT]: '충돌이 감지되었습니다',
    [ApiErrorCode.METHOD_NOT_ALLOWED]: '허용되지 않은 메서드',
    [ApiErrorCode.VALIDATION_ERROR]: '검증 실패',
    [ApiErrorCode.RATE_LIMITED]: '요청이 너무 많습니다',
    [ApiErrorCode.INTERNAL_ERROR]: '서버 내부 오류',
    [ApiErrorCode.SERVICE_UNAVAILABLE]: '서비스 이용 불가',
    [ApiErrorCode.TIMEOUT]: '요청 시간 초과',
    [ApiErrorCode.NETWORK_ERROR]: '서버에 연결할 수 없습니다. 네트워크 연결을 확인하세요.',
  },

  [Language.Russian]: {
    [ApiErrorCode.UNHANDLED_ERROR]: 'Произошла непредвиденная ошибка',
    [ApiErrorCode.BAD_REQUEST]: 'Неверный запрос',
    [ApiErrorCode.UNAUTHORIZED]: 'Требуется аутентификация',
    [ApiErrorCode.FORBIDDEN]: 'Доступ запрещен',
    [ApiErrorCode.NOT_FOUND]: 'Ресурс не найден',
    [ApiErrorCode.CONFLICT]: 'Обнаружен конфликт',
    [ApiErrorCode.METHOD_NOT_ALLOWED]: 'Метод не разрешен',
    [ApiErrorCode.VALIDATION_ERROR]: 'Ошибка валидации',
    [ApiErrorCode.RATE_LIMITED]: 'Слишком много запросов',
    [ApiErrorCode.INTERNAL_ERROR]: 'Внутренняя ошибка сервера',
    [ApiErrorCode.SERVICE_UNAVAILABLE]: 'Сервис недоступен',
    [ApiErrorCode.TIMEOUT]: 'Тайм-аут запроса',
    [ApiErrorCode.NETWORK_ERROR]:
      'Не удается подключиться к серверу. Проверьте сетевое подключение.',
  },

  [Language.Dutch]: {
    [ApiErrorCode.UNHANDLED_ERROR]: 'Er is een onverwachte fout opgetreden',
    [ApiErrorCode.BAD_REQUEST]: 'Ongeldig verzoek',
    [ApiErrorCode.UNAUTHORIZED]: 'Authenticatie vereist',
    [ApiErrorCode.FORBIDDEN]: 'Toegang geweigerd',
    [ApiErrorCode.NOT_FOUND]: 'Bron niet gevonden',
    [ApiErrorCode.CONFLICT]: 'Conflict gedetecteerd',
    [ApiErrorCode.METHOD_NOT_ALLOWED]: 'Methode niet toegestaan',
    [ApiErrorCode.VALIDATION_ERROR]: 'Validatie mislukt',
    [ApiErrorCode.RATE_LIMITED]: 'Te veel verzoeken',
    [ApiErrorCode.INTERNAL_ERROR]: 'Interne serverfout',
    [ApiErrorCode.SERVICE_UNAVAILABLE]: 'Service niet beschikbaar',
    [ApiErrorCode.TIMEOUT]: 'Verzoek timeout',
    [ApiErrorCode.NETWORK_ERROR]:
      'Kan geen verbinding maken met de server. Controleer uw netwerkverbinding.',
  },

  [Language.Arabic]: {
    [ApiErrorCode.UNHANDLED_ERROR]: 'حدث خطأ غير متوقع',
    [ApiErrorCode.BAD_REQUEST]: 'طلب غير صالح',
    [ApiErrorCode.UNAUTHORIZED]: 'المصادقة مطلوبة',
    [ApiErrorCode.FORBIDDEN]: 'تم رفض الوصول',
    [ApiErrorCode.NOT_FOUND]: 'المورد غير موجود',
    [ApiErrorCode.CONFLICT]: 'تم اكتشاف تعارض',
    [ApiErrorCode.METHOD_NOT_ALLOWED]: 'الطريقة غير مسموح بها',
    [ApiErrorCode.VALIDATION_ERROR]: 'فشل التحقق',
    [ApiErrorCode.RATE_LIMITED]: 'طلبات كثيرة جداً',
    [ApiErrorCode.INTERNAL_ERROR]: 'خطأ داخلي في الخادم',
    [ApiErrorCode.SERVICE_UNAVAILABLE]: 'الخدمة غير متوفرة',
    [ApiErrorCode.TIMEOUT]: 'انتهت مهلة الطلب',
    [ApiErrorCode.NETWORK_ERROR]: 'تعذر الاتصال بالخادم. يرجى التحقق من اتصال الشبكة.',
  },

  [Language.Swedish]: {
    [ApiErrorCode.UNHANDLED_ERROR]: 'Ett oväntat fel inträffade',
    [ApiErrorCode.BAD_REQUEST]: 'Ogiltig begäran',
    [ApiErrorCode.UNAUTHORIZED]: 'Autentisering krävs',
    [ApiErrorCode.FORBIDDEN]: 'Åtkomst nekad',
    [ApiErrorCode.NOT_FOUND]: 'Resursen hittades inte',
    [ApiErrorCode.CONFLICT]: 'Konflikt upptäckt',
    [ApiErrorCode.METHOD_NOT_ALLOWED]: 'Metoden är inte tillåten',
    [ApiErrorCode.VALIDATION_ERROR]: 'Validering misslyckades',
    [ApiErrorCode.RATE_LIMITED]: 'För många förfrågningar',
    [ApiErrorCode.INTERNAL_ERROR]: 'Internt serverfel',
    [ApiErrorCode.SERVICE_UNAVAILABLE]: 'Tjänsten är inte tillgänglig',
    [ApiErrorCode.TIMEOUT]: 'Timeout för begäran',
    [ApiErrorCode.NETWORK_ERROR]:
      'Kan inte ansluta till servern. Kontrollera din nätverksanslutning.',
  },

  [Language.Norwegian]: {
    [ApiErrorCode.UNHANDLED_ERROR]: 'En uventet feil oppstod',
    [ApiErrorCode.BAD_REQUEST]: 'Ugyldig forespørsel',
    [ApiErrorCode.UNAUTHORIZED]: 'Autentisering kreves',
    [ApiErrorCode.FORBIDDEN]: 'Tilgang nektet',
    [ApiErrorCode.NOT_FOUND]: 'Ressursen ble ikke funnet',
    [ApiErrorCode.CONFLICT]: 'Konflikt oppdaget',
    [ApiErrorCode.METHOD_NOT_ALLOWED]: 'Metoden er ikke tillatt',
    [ApiErrorCode.VALIDATION_ERROR]: 'Validering mislyktes',
    [ApiErrorCode.RATE_LIMITED]: 'For mange forespørsler',
    [ApiErrorCode.INTERNAL_ERROR]: 'Intern serverfeil',
    [ApiErrorCode.SERVICE_UNAVAILABLE]: 'Tjenesten er utilgjengelig',
    [ApiErrorCode.TIMEOUT]: 'Forespørselen ble tidsavbrutt',
    [ApiErrorCode.NETWORK_ERROR]: 'Kan ikke koble til serveren. Sjekk nettverkstilkoblingen.',
  },

  [Language.Danish]: {
    [ApiErrorCode.UNHANDLED_ERROR]: 'Der opstod en uventet fejl',
    [ApiErrorCode.BAD_REQUEST]: 'Ugyldig anmodning',
    [ApiErrorCode.UNAUTHORIZED]: 'Godkendelse påkrævet',
    [ApiErrorCode.FORBIDDEN]: 'Adgang nægtet',
    [ApiErrorCode.NOT_FOUND]: 'Ressource ikke fundet',
    [ApiErrorCode.CONFLICT]: 'Konflikt registreret',
    [ApiErrorCode.METHOD_NOT_ALLOWED]: 'Metode ikke tilladt',
    [ApiErrorCode.VALIDATION_ERROR]: 'Validering mislykkedes',
    [ApiErrorCode.RATE_LIMITED]: 'For mange anmodninger',
    [ApiErrorCode.INTERNAL_ERROR]: 'Intern serverfejl',
    [ApiErrorCode.SERVICE_UNAVAILABLE]: 'Tjeneste utilgængelig',
    [ApiErrorCode.TIMEOUT]: 'Anmodningstimeout',
    [ApiErrorCode.NETWORK_ERROR]:
      'Kan ikke oprette forbindelse til serveren. Tjek din netværksforbindelse.',
  },

  [Language.Finnish]: {
    [ApiErrorCode.UNHANDLED_ERROR]: 'Odottamaton virhe tapahtui',
    [ApiErrorCode.BAD_REQUEST]: 'Virheellinen pyyntö',
    [ApiErrorCode.UNAUTHORIZED]: 'Todennus vaaditaan',
    [ApiErrorCode.FORBIDDEN]: 'Pääsy evätty',
    [ApiErrorCode.NOT_FOUND]: 'Resurssia ei löytynyt',
    [ApiErrorCode.CONFLICT]: 'Ristiriita havaittu',
    [ApiErrorCode.METHOD_NOT_ALLOWED]: 'Menetelmä ei sallittu',
    [ApiErrorCode.VALIDATION_ERROR]: 'Vahvistus epäonnistui',
    [ApiErrorCode.RATE_LIMITED]: 'Liian monta pyyntöä',
    [ApiErrorCode.INTERNAL_ERROR]: 'Sisäinen palvelinvirhe',
    [ApiErrorCode.SERVICE_UNAVAILABLE]: 'Palvelu ei saatavilla',
    [ApiErrorCode.TIMEOUT]: 'Pyyntö aikakatkaistiin',
    [ApiErrorCode.NETWORK_ERROR]: 'Palvelimeen ei saada yhteyttä. Tarkista verkkoyhteytesi.',
  },

  [Language.Polish]: {
    [ApiErrorCode.UNHANDLED_ERROR]: 'Wystąpił nieoczekiwany błąd',
    [ApiErrorCode.BAD_REQUEST]: 'Nieprawidłowe żądanie',
    [ApiErrorCode.UNAUTHORIZED]: 'Wymagane uwierzytelnienie',
    [ApiErrorCode.FORBIDDEN]: 'Dostęp zabroniony',
    [ApiErrorCode.NOT_FOUND]: 'Zasób nie znaleziony',
    [ApiErrorCode.CONFLICT]: 'Wykryto konflikt',
    [ApiErrorCode.METHOD_NOT_ALLOWED]: 'Metoda niedozwolona',
    [ApiErrorCode.VALIDATION_ERROR]: 'Walidacja nie powiodła się',
    [ApiErrorCode.RATE_LIMITED]: 'Zbyt wiele żądań',
    [ApiErrorCode.INTERNAL_ERROR]: 'Wewnętrzny błąd serwera',
    [ApiErrorCode.SERVICE_UNAVAILABLE]: 'Usługa niedostępna',
    [ApiErrorCode.TIMEOUT]: 'Limit czasu żądania',
    [ApiErrorCode.NETWORK_ERROR]: 'Nie można połączyć się z serwerem. Sprawdź połączenie sieciowe.',
  },

  [Language.Hindi]: {
    [ApiErrorCode.UNHANDLED_ERROR]: 'एक अप्रत्याशित त्रुटि हुई',
    [ApiErrorCode.BAD_REQUEST]: 'अमान्य अनुरोध',
    [ApiErrorCode.UNAUTHORIZED]: 'प्रमाणीकरण आवश्यक है',
    [ApiErrorCode.FORBIDDEN]: 'पहुंच अस्वीकृत',
    [ApiErrorCode.NOT_FOUND]: 'संसाधन नहीं मिला',
    [ApiErrorCode.CONFLICT]: 'विरोध का पता चला',
    [ApiErrorCode.METHOD_NOT_ALLOWED]: 'विधि अनुमत नहीं है',
    [ApiErrorCode.VALIDATION_ERROR]: 'सत्यापन विफल',
    [ApiErrorCode.RATE_LIMITED]: 'बहुत अधिक अनुरोध',
    [ApiErrorCode.INTERNAL_ERROR]: 'आंतरिक सर्वर त्रुटि',
    [ApiErrorCode.SERVICE_UNAVAILABLE]: 'सेवा अनुपलब्ध',
    [ApiErrorCode.TIMEOUT]: 'अनुरोध समय समाप्त',
    [ApiErrorCode.NETWORK_ERROR]: 'सर्वर से कनेक्ट नहीं हो सका। कृपया अपना नेटवर्क कनेक्शन जांचें।',
  },
};

export function getLocalizedErrorMessage(
  code: string,
  language: Language = Language.English,
  fallback?: string,
): string {
  const langMessages = messages[language] ?? messages[Language.English];
  const localized = langMessages[code as ApiErrorCode];
  return localized ?? fallback ?? code;
}

export function hasLocalizedMessage(code: string, language: Language = Language.English): boolean {
  const langMessages = messages[language] ?? messages[Language.English];
  return code in langMessages;
}
