export const ACP_ACTIVE_DATE_DEBOUNCE = 100;

export enum ACP_DATE_OPTION_TYPE {
  DATE_DIFF = 1,
  LAST_MONTH = 2,
  THIS_MONTH = 3,
  YEAR_TO_DATE = 4,
  CUSTOM = 5,
  MONTH_TO_DATE = 6,
  WEEK_TO_DATE = 7,
}
