name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - uses: nrwl/nx-set-shas@v4

      - name: Run lint
        run: pnpm exec nx affected -t lint --exclude demo-app --parallel=3

      - name: Run test
        run: pnpm exec nx affected -t test --exclude demo-app --parallel=3

      - name: Run build
        run: pnpm exec nx affected -t build --exclude demo-app --parallel=3
